package postfix;

public class StackUnderflowException extends Exception {

	/**
	 * serialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 3866301275271324783L;
	
	public StackUnderflowException() {
		
	}
	
	public StackUnderflowException(String message) {
		super(message);
	}
	
	public StackUnderflowException(String message, Throwable cause) {
		super(message, cause);
	}
}
